"""
Items Router - REST API Endpoints for Inventory Items
======================================================

This module provides CRUD (Create, Read, Update, Delete) endpoints for managing inventory items.

Endpoints:
- GET    /api/v1/items              - List all items (with pagination)
- GET    /api/v1/items/{item_id}    - Get specific item details
- POST   /api/v1/items              - Create new item
- PUT    /api/v1/items/{item_id}    - Update existing item
- DELETE /api/v1/items/{item_id}    - Delete item

Data Models:
- ItemCreate: Schema for creating new items
- ItemUpdate: Schema for updating items (all fields optional)
- ItemResponse: Schema for API responses (includes database-managed fields)

Error Handling:
- Returns 404 (Not Found) when item doesn't exist
- Returns 422 (Unprocessable Entity) when request data is invalid
- Returns 500 (Server Error) for database issues

Pagination:
- Supports skip/limit parameters for retrieving large datasets
- Default limit: 100 items per request
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from app.database import get_db
from app.models.inventory import Item
from pydantic import BaseModel
from datetime import datetime

# Create router instance - all routes in this file will use /items prefix (in main.py)
router = APIRouter()

# ==========================================
# PYDANTIC SCHEMAS - Data Validation
# ==========================================

class ItemCreate(BaseModel):
    """
    Schema for creating a new inventory item.
    
    Used in: POST /items
    
    Fields:
        name (str): Product name/description - required
        quantity (int): Initial stock quantity - required
        price (float): Unit price in dollars - required
    
    Note: id and timestamps are generated by the server
    """
    name: str
    quantity: int
    price: float


class ItemUpdate(BaseModel):
    """
    Schema for updating an existing inventory item.
    
    Used in: PUT /items/{item_id}
    
    Fields:
        name (str, optional): New product name - leave null to keep existing
        quantity (int, optional): New stock quantity - leave null to keep existing
        price (float, optional): New unit price - leave null to keep existing
    
    All fields are optional, allowing partial updates.
    Only provided fields will be updated; null fields are ignored.
    """
    name: str = None
    quantity: int = None
    price: float = None


class ItemResponse(BaseModel):
    """
    Schema for API responses containing item data.
    
    Used in: GET, POST, PUT responses
    
    Fields:
        id (int): Unique database identifier
        name (str): Product name
        quantity (int): Current stock level
        price (float): Unit price
        created_at (datetime): When item was created
    
    Config.from_attributes:
        Enables Pydantic to read ORM model attributes directly
        Converts SQLAlchemy model objects to Pydantic models
    """
    id: int
    name: str
    quantity: int
    price: float
    created_at: datetime

    class Config:
        from_attributes = True  # Read from SQLAlchemy ORM attributes


# ==========================================
# ENDPOINTS - REST API Routes
# ==========================================

@router.get("/items", response_model=List[ItemResponse])
async def list_items(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    """
    Retrieve all inventory items with pagination support.
    
    Endpoint: GET /api/v1/items
    
    Query Parameters:
        skip (int): Number of items to skip - default 0
        limit (int): Maximum items to return - default 100, max 100
    
    Returns:
        List[ItemResponse]: Array of item objects
    
    Example:
        GET /api/v1/items?skip=0&limit=50 → Returns first 50 items
        GET /api/v1/items → Returns up to 100 items
    
    Status Codes:
        200: Success
        400: Invalid pagination parameters
    """
    items = db.query(Item).offset(skip).limit(limit).all()
    return items


@router.get("/items/{item_id}", response_model=ItemResponse)
async def get_item(item_id: int, db: Session = Depends(get_db)):
    """
    Retrieve a specific item by its ID.
    
    Endpoint: GET /api/v1/items/{item_id}
    
    Path Parameters:
        item_id (int): Unique identifier of the item to retrieve
    
    Returns:
        ItemResponse: Item object with all details
    
    Status Codes:
        200: Item found and returned
        404: Item not found
    
    Example:
        GET /api/v1/items/5 → Returns item with ID 5
    """
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return item


@router.post("/items", response_model=ItemResponse)
async def create_item(item: ItemCreate, db: Session = Depends(get_db)):
    """
    Create a new inventory item.
    
    Endpoint: POST /api/v1/items
    
    Request Body:
        ItemCreate: Object containing name, quantity, price
    
    Returns:
        ItemResponse: Newly created item with auto-generated id and timestamps
    
    Status Codes:
        200: Item created successfully
        422: Invalid request data (missing fields, wrong types)
    
    Database Operations:
        1. Create new Item object
        2. Add to session
        3. Commit transaction
        4. Refresh to get database-generated id and timestamps
    
    Example Request:
        POST /api/v1/items
        {
            "name": "Widget A",
            "quantity": 100,
            "price": 29.99
        }
    
    Example Response:
        {
            "id": 1,
            "name": "Widget A",
            "quantity": 100,
            "price": 29.99,
            "created_at": "2024-02-03T12:34:56"
        }
    """
    db_item = Item(
        name=item.name,
        quantity=item.quantity,
        price=item.price
    )
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item


@router.put("/items/{item_id}", response_model=ItemResponse)
async def update_item(item_id: int, item: ItemUpdate, db: Session = Depends(get_db)):
    """
    Update an existing inventory item.
    
    Endpoint: PUT /api/v1/items/{item_id}
    
    Path Parameters:
        item_id (int): ID of item to update
    
    Request Body:
        ItemUpdate: Object with fields to update (null fields are ignored)
    
    Returns:
        ItemResponse: Updated item object
    
    Status Codes:
        200: Item updated successfully
        404: Item not found
        422: Invalid request data
    
    Database Operations:
        1. Query item by id
        2. Check if exists (raise 404 if not)
        3. Update only provided (non-null) fields
        4. Update timestamp to current time
        5. Commit and refresh
    
    Example Request:
        PUT /api/v1/items/5
        {
            "quantity": 150,
            "price": null
        }
        Result: quantity updated to 150, price unchanged
    """
    db_item = db.query(Item).filter(Item.id == item_id).first()
    if not db_item:
        raise HTTPException(status_code=404, detail="Item not found")
    
    # Only update fields that were provided (not null)
    if item.name is not None:
        db_item.name = item.name
    if item.quantity is not None:
        db_item.quantity = item.quantity
    if item.price is not None:
        db_item.price = item.price
    
    # Update the modified timestamp
    db_item.updated_at = datetime.utcnow()
    db.commit()
    db.refresh(db_item)
    return db_item


@router.delete("/items/{item_id}")
async def delete_item(item_id: int, db: Session = Depends(get_db)):
    """
    Delete an inventory item and all its related transactions.
    
    Endpoint: DELETE /api/v1/items/{item_id}
    
    Path Parameters:
        item_id (int): ID of item to delete
    
    Returns:
        dict: Confirmation message
    
    Status Codes:
        200: Item deleted successfully
        404: Item not found
    
    Database Operations:
        1. Query item by id
        2. Check if exists (raise 404 if not)
        3. Delete item (cascade also deletes related transactions)
        4. Commit transaction
    
    Important Notes:
        - Deletion is permanent and irreversible
        - All transactions linked to this item are also deleted (cascade delete)
        - Consider adding soft delete (archive) for audit trail in production
    
    Example Response:
        {
            "message": "Item deleted successfully"
        }
    """
    db_item = db.query(Item).filter(Item.id == item_id).first()
    if not db_item:
        raise HTTPException(status_code=404, detail="Item not found")
    
    db.delete(db_item)
    db.commit()
    return {"message": "Item deleted successfully"}
