"""
Transactions Router - REST API Endpoints for Inventory Transactions
====================================================================

This module provides CRUD endpoints for managing inventory transactions.
Transactions represent movements/changes to inventory items.

Endpoints:
- GET    /api/v1/transactions              - List all transactions (newest first)
- GET    /api/v1/transactions/{txn_id}    - Get specific transaction
- POST   /api/v1/transactions              - Record new transaction
- DELETE /api/v1/transactions/{txn_id}    - Delete transaction record

Data Models:
- TransactionCreate: Schema for creating new transactions
- TransactionResponse: Schema for API responses

Transaction Types:
- 'sale': Item sold to customer (inventory decreases)
- 'purchase': Item purchased/received (inventory increases)
- 'adjustment': Inventory adjustment/correction
- 'return': Item returned by customer (inventory increases)

Error Handling:
- Returns 404 (Not Found) when transaction doesn't exist
- Returns 422 (Unprocessable Entity) when request data is invalid
- Returns 500 (Server Error) for database issues
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from datetime import datetime
from app.database import get_db
from app.models.inventory import Transaction
from pydantic import BaseModel

# Create router instance - all routes in this file will use /transactions prefix (in main.py)
router = APIRouter()

# ==========================================
# PYDANTIC SCHEMAS - Data Validation
# ==========================================

class TransactionCreate(BaseModel):
    """
    Schema for creating a new transaction record.
    
    Used in: POST /transactions
    
    Fields:
        type (str): Transaction type - must be one of:
                   'sale', 'purchase', 'adjustment', 'return'
        item_id (int): ID of the item involved in transaction
        quantity (int): Number of units in transaction
        amount (float): Monetary value of transaction in dollars
    
    Note: id and created_at are generated by the server
    """
    type: str                           # "sale", "purchase", "adjustment", "return"
    item_id: int                        # ID of related item
    quantity: int                       # Units involved
    amount: float                       # Dollar amount


class TransactionResponse(BaseModel):
    """
    Schema for API responses containing transaction data.
    
    Used in: GET, POST, DELETE responses
    
    Fields:
        id (int): Unique database identifier
        type (str): Transaction type
        item_id (int): Related item ID
        quantity (int): Units involved
        amount (float): Transaction amount
        created_at (datetime): When transaction was created
    
    Config.from_attributes:
        Enables Pydantic to read ORM model attributes directly
        Converts SQLAlchemy model objects to Pydantic models
    """
    id: int
    type: str
    item_id: int
    quantity: int
    amount: float
    created_at: datetime

    class Config:
        from_attributes = True  # Read from SQLAlchemy ORM attributes


# ==========================================
# ENDPOINTS - REST API Routes
# ==========================================

@router.get("/transactions", response_model=List[TransactionResponse])
async def list_transactions(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db)
):
    """
    Retrieve all transactions, sorted by newest first.
    
    Endpoint: GET /api/v1/transactions
    
    Query Parameters:
        skip (int): Number of transactions to skip - default 0
        limit (int): Maximum transactions to return - default 100
    
    Returns:
        List[TransactionResponse]: Array of transaction objects, newest first
    
    Sorting:
        Transactions are sorted by created_at in descending order (newest first)
        This shows recent activity at the top
    
    Status Codes:
        200: Success
        400: Invalid pagination parameters
    
    Example:
        GET /api/v1/transactions → Returns up to 100 newest transactions
        GET /api/v1/transactions?skip=0&limit=50 → Returns first 50 newest
    """
    # Query transactions sorted by creation date (newest first)
    transactions = db.query(Transaction).order_by(Transaction.created_at.desc()).offset(skip).limit(limit).all()
    return transactions


@router.get("/transactions/{transaction_id}", response_model=TransactionResponse)
async def get_transaction(transaction_id: int, db: Session = Depends(get_db)):
    """
    Retrieve a specific transaction by its ID.
    
    Endpoint: GET /api/v1/transactions/{transaction_id}
    
    Path Parameters:
        transaction_id (int): Unique identifier of transaction to retrieve
    
    Returns:
        TransactionResponse: Transaction object with all details
    
    Status Codes:
        200: Transaction found and returned
        404: Transaction not found
    
    Example:
        GET /api/v1/transactions/12 → Returns transaction with ID 12
    """
    transaction = db.query(Transaction).filter(Transaction.id == transaction_id).first()
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction not found")
    return transaction


@router.post("/transactions", response_model=TransactionResponse)
async def create_transaction(txn: TransactionCreate, db: Session = Depends(get_db)):
    """
    Create a new transaction record.
    
    Endpoint: POST /api/v1/transactions
    
    Request Body:
        TransactionCreate: Object containing type, item_id, quantity, amount
    
    Returns:
        TransactionResponse: Newly created transaction with auto-generated id and timestamp
    
    Status Codes:
        200: Transaction created successfully
        422: Invalid request data (missing fields, wrong types)
    
    Transaction Types:
        - 'sale': Item sold to customer (stock decreases)
        - 'purchase': Item purchased/received (stock increases)
        - 'adjustment': Inventory correction/adjustment
        - 'return': Item returned by customer (stock increases)
    
    Database Operations:
        1. Create new Transaction object from request data
        2. Add to session
        3. Commit transaction
        4. Refresh to get database-generated id and timestamp
    
    Note on Inventory Updates:
        This API records the transaction. You may need separate logic to:
        - Update item quantity based on transaction type
        - Validate item exists before creating transaction
        - Apply business rules (e.g., prevent overselling)
    
    Example Request:
        POST /api/v1/transactions
        {
            "type": "sale",
            "item_id": 5,
            "quantity": 10,
            "amount": 299.90
        }
    
    Example Response:
        {
            "id": 42,
            "type": "sale",
            "item_id": 5,
            "quantity": 10,
            "amount": 299.90,
            "created_at": "2024-02-03T12:34:56"
        }
    """
    db_transaction = Transaction(
        type=txn.type,
        item_id=txn.item_id,
        quantity=txn.quantity,
        amount=txn.amount
    )
    db.add(db_transaction)
    db.commit()
    db.refresh(db_transaction)
    return db_transaction


@router.delete("/transactions/{transaction_id}")
async def delete_transaction(transaction_id: int, db: Session = Depends(get_db)):
    """
    Delete a transaction record from the system.
    
    Endpoint: DELETE /api/v1/transactions/{transaction_id}
    
    Path Parameters:
        transaction_id (int): ID of transaction to delete
    
    Returns:
        dict: Confirmation message
    
    Status Codes:
        200: Transaction deleted successfully
        404: Transaction not found
    
    Database Operations:
        1. Query transaction by id
        2. Check if exists (raise 404 if not)
        3. Delete transaction
        4. Commit transaction
    
    Important Notes:
        - Deletion is permanent and irreversible
        - Does NOT automatically adjust item quantities
        - For audit trail, consider adding soft delete (archive) in production
        - Frontend should warn users before allowing deletion
    
    Example Response:
        {
            "message": "Transaction deleted successfully"
        }
    """
    db_transaction = db.query(Transaction).filter(Transaction.id == transaction_id).first()
    if not db_transaction:
        raise HTTPException(status_code=404, detail="Transaction not found")
    
    db.delete(db_transaction)
    db.commit()
    return {"message": "Transaction deleted successfully"}
